import React, { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { FileText, Download, Mail, Activity, Users, IndianRupee, Stethoscope, AlertTriangle, Printer } from 'lucide-react';
import { useEnterpriseStore } from '../../../store/useEnterpriseStore';
import { briefingService } from '../../../services/briefingService';
import { Button } from '@/components/ui/button';

export default function BriefingDashboard() {
  const { dailyBriefings } = useEnterpriseStore();
  const [isGenerating, setIsGenerating] = useState(false);

  // Get the most recent briefing
  const latestBriefing = dailyBriefings[0];

  const handleGenerate = async () => {
    setIsGenerating(true);
    await briefingService.generateDailyBriefing();
    setTimeout(() => setIsGenerating(false), 1000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between no-print">
        <div>
          <h1 className="text-3xl font-bold text-foreground flex items-center gap-3">
            <FileText className="w-8 h-8 text-primary" />
            AI Daily Briefing
          </h1>
          <p className="text-muted-foreground mt-1">Hospital-wide operational report generated by AI</p>
        </div>
        <div className="flex gap-3">
          <Button variant="outline" onClick={handlePrint} className="bg-background">
            <Printer className="w-4 h-4 mr-2" /> Print PDF
          </Button>
          <Button variant="outline" className="bg-background text-primary border-primary">
            <Mail className="w-4 h-4 mr-2" /> Email Briefing
          </Button>
          <Button 
            onClick={handleGenerate} 
            disabled={isGenerating}
            className="bg-primary hover:bg-primary/90 text-primary-foreground"
          >
            {isGenerating ? 'Generating...' : 'Generate New Briefing'}
          </Button>
        </div>
      </div>

      {latestBriefing ? (
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-card border border-border rounded-2xl p-8 max-w-5xl mx-auto shadow-2xl print-layout"
        >
          {/* Header */}
          <div className="flex justify-between items-center border-b border-border pb-6 mb-8">
            <div>
              <h2 className="text-4xl font-black tracking-widest text-foreground">HOSPITAL<span className="text-primary">OS</span></h2>
              <p className="text-muted-foreground uppercase tracking-wider text-sm mt-1">Daily Operations Briefing</p>
            </div>
            <div className="text-right">
              <p className="text-lg font-semibold text-foreground">Date: {new Date(latestBriefing.date).toLocaleDateString()}</p>
              <div className="inline-flex items-center gap-2 mt-2 bg-primary/10 px-4 py-2 rounded-full border border-primary/20">
                <Activity className="w-5 h-5 text-primary" />
                <span className="font-bold text-primary">Health Score: {latestBriefing.hospitalHealthScore}/100</span>
              </div>
            </div>
          </div>

          {/* Core Metrics */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6 mb-8">
            <div className="bg-background rounded-xl p-4 border border-border">
              <Users className="w-6 h-6 text-blue-500 mb-2" />
              <p className="text-muted-foreground text-sm">Total Admissions</p>
              <p className="text-2xl font-bold text-foreground">{latestBriefing.admissions}</p>
            </div>
            <div className="bg-background rounded-xl p-4 border border-border">
              <CheckSquare className="w-6 h-6 text-green-500 mb-2" />
              <p className="text-muted-foreground text-sm">Discharges</p>
              <p className="text-2xl font-bold text-foreground">{latestBriefing.discharges}</p>
            </div>
            <div className="bg-background rounded-xl p-4 border border-border">
              <AlertTriangle className="w-6 h-6 text-orange-500 mb-2" />
              <p className="text-muted-foreground text-sm">Critical Patients</p>
              <p className="text-2xl font-bold text-foreground">{latestBriefing.criticalPatients}</p>
            </div>
            <div className="bg-background rounded-xl p-4 border border-border">
              <IndianRupee className="w-6 h-6 text-green-500 mb-2" />
              <p className="text-muted-foreground text-sm">Revenue Today</p>
              <p className="text-2xl font-bold text-foreground">₹{latestBriefing.revenue.toLocaleString()}</p>
            </div>
          </div>

          {/* Activity Section */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
            <div>
              <h3 className="text-xl font-bold text-foreground mb-4 border-b border-border pb-2">Clinical Activity</h3>
              <ul className="space-y-4">
                <li className="flex justify-between items-center bg-background p-3 rounded-lg border border-border">
                  <span className="text-muted-foreground flex items-center gap-2"><Stethoscope className="w-4 h-4" /> Appointments</span>
                  <span className="font-bold text-foreground">{latestBriefing.appointments}</span>
                </li>
                <li className="flex justify-between items-center bg-background p-3 rounded-lg border border-border">
                  <span className="text-muted-foreground flex items-center gap-2"><Activity className="w-4 h-4" /> Pending Lab Reports</span>
                  <span className="font-bold text-foreground">{latestBriefing.pendingLabReports}</span>
                </li>
              </ul>
            </div>
            <div>
              <h3 className="text-xl font-bold text-foreground mb-4 border-b border-border pb-2">Top AI Recommendations</h3>
              <ul className="space-y-3">
                {latestBriefing.recommendations.map((rec, idx) => (
                  <li key={idx} className="bg-primary/5 text-primary p-3 rounded-lg border border-primary/20 text-sm font-medium flex gap-2">
                    <span className="mt-0.5">•</span> <span>{rec}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
          
          {/* Footer */}
          <div className="text-center pt-8 border-t border-border text-muted-foreground text-sm">
            Generated automatically by HospitalOS Enterprise AI Engine
          </div>
        </motion.div>
      ) : (
        <div className="text-center py-20 bg-card rounded-2xl border border-border">
          <FileText className="w-16 h-16 mx-auto mb-4 text-muted-foreground opacity-50" />
          <h3 className="text-xl font-semibold text-foreground mb-2">No Briefings Found</h3>
          <p className="text-muted-foreground mb-6">Generate the first daily briefing to see the AI report.</p>
          <Button onClick={handleGenerate}>Generate First Briefing</Button>
        </div>
      )}
      
      {/* CSS for printing */}
      <style>{`
        @media print {
          body * { visibility: hidden; }
          .print-layout, .print-layout * { visibility: visible; }
          .print-layout { position: absolute; left: 0; top: 0; width: 100%; border: none; box-shadow: none; }
          .no-print { display: none !important; }
        }
      `}</style>
    </div>
  );
}

function CheckSquare(props: any) {
  return (
    <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <polyline points="9 11 12 14 22 4"></polyline>
      <path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"></path>
    </svg>
  );
}
